language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
    - pecl install ssh2
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
script:
    - vendor/bin/phpunit -c phpunit.xml
