language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
    - sudo apt-get update
    - sudo apt-get install libssh2-1-dev libssh2-php
    - touch .noninteractive && pecl install -f ssh2 < .noninteractive
    - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - php -m | grep ssh2
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
script:
    - vendor/bin/phpunit -c phpunit.xml
