language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
    - sudo apt-get update
    - sudo apt-get install libssh2-1-dev libssh2-php
    - touch .noninteractive && pecl install -f ssh2 < .noninteractive
    - composer selfupdate
    - composer install
script:
    - vendor/bin/phpunit -c phpunit.xml
